version: "3"

services:
  web:
    build: .
    image: achooan/$APP_NAME:$CIRCLE_BRANCH-$CIRCLE_SHA1
    ports:
      - 80:$APP_PORT
    container_name: simple-ec-app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    container_name: simple-ec-mongo

volumes:
  data-volume: