version: 2

refs:
  docker: &docker
    docker: 
      - image: circleci/node:10.15
      - image: circleci/mongo:latest

jobs:
  build:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t achooan/$APP_NAME .
      - run:
          name: Save Docker Image
          command: |
            mkdir -p /tmp/docker-image
            docker save -o /tmp/docker-image/app.tar achooan/$APP_NAME
      - persist_to_workspace:
          root: /tmp/docker-image
          paths:
            - app.tar

  deploy:
    <<: *docker
    steps:
      - attach_workspace:
          at: /tmp/docker-image
      - setup_remote_docker
      - run:
          name: Load Docker Image
          command: |
            docker load -i /tmp/docker-image/app.tar
      - run:
          name: Tag Docker Image
          command: |
            docker tag achooan/$APP_NAME achooan/$APP_NAME-$CIRCLE_SHA1
            docker tag achooan/$APP_NAME achooan/$APP_NAME:latest
      - run:
          name: Login to DockerHub
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PW
      - run:
          name: Push Docker Image
          command: |
            docker push achooan/$APP_NAME-$CIRCLE_SHA1
            docker push achooan/$APP_NAME:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
     